### ISSUE TITLE
Example command is wrong

### ISSUE THREAD

**Issue by schmirob** [amc-nu/RosImageFolderPublisher#1]
In example command missed ":". The correct command should be

`rosrun image_folder_publisher image_folder_publisher.py _image_folder:=/PATH/Images _topic_name:=/image_topic`

**Comment by amc-nu** [comment]
Thanks for pointing it out. Fixed [here](https://github.com/amc-nu/RosImageFolderPublisher/commit/e31bb5d1540be6d1cf97e20671cfe6de1b936e5d)
